# Generated by Django 4.0 on 2022-02-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('m', 'Main'), ('p', 'Paired')], default=None, max_length=6),
            preserve_default=False,
        ),
    ]
