# Generated by Django 4.0 on 2022-02-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bundle_delete_paireditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=32)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AlterField(
            model_name='bundle',
            name='sub1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='shop.paired'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='sub2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item2', to='shop.paired'),
        ),
    ]
